# Generated by Django 2.2 on 2020-04-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('max_users', models.IntegerField(default=10)),
                ('max_time', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'mode',
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(default='Red Army')),
                ('image_id', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'nation',
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(default='Jia lissa')),
                ('weapon_name', models.TextField()),
                ('attack', models.IntegerField(null=True)),
                ('armor', models.IntegerField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('accuracy', models.IntegerField(null=True)),
                ('rate_of_fire', models.IntegerField(null=True)),
                ('max_health', models.IntegerField(null=True)),
                ('current_health', models.IntegerField(null=True)),
                ('max_ammo', models.IntegerField(null=True)),
                ('current_ammo', models.IntegerField(null=True)),
                ('max_clip', models.IntegerField(null=True)),
                ('current_clip', models.IntegerField(null=True)),
                ('image_id', models.IntegerField(null=True)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.Nation')),
            ],
            options={
                'db_table': 'robot',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start_time', models.TextField(default='00:00:00 00/00/00')),
                ('end_time', models.TextField(default='00:00:00 00/00/00')),
                ('is_private', models.IntegerField(default=False)),
                ('result', models.TextField(default='kir sokhari ba ablimu')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.Mode')),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
