# Generated by Django 2.2 on 2020-04-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='result',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
