# Generated by Django 3.0.2 on 2020-02-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sniper', models.IntegerField(default=0)),
                ('assault', models.IntegerField(default=0)),
                ('engineer', models.IntegerField(default=0)),
                ('support', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Daate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('max_users', models.IntegerField()),
                ('max_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(default='Elena Koshka')),
                ('image_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('total_kill', models.IntegerField(default=0)),
                ('total_death', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('coin', models.IntegerField(default=0)),
                ('extra_health', models.IntegerField(default=0)),
                ('special_attacks', models.IntegerField(default=0)),
                ('bullet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Bullet')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.TimeField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nickname', models.TextField(default='guest')),
                ('phone_number', models.TextField(default='000000000', unique=True)),
                ('token', models.TextField(default='', null=True, unique=True)),
                ('last_code_send', models.IntegerField(default=0, null=True)),
                ('avatar_url', models.TextField(default='', null=True)),
                ('profile', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
                ('wallet', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(default='Jia lissa')),
                ('weapon_name', models.TextField()),
                ('attack', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('rate_of_fire', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('current_health', models.IntegerField()),
                ('max_ammo', models.IntegerField()),
                ('current_ammo', models.IntegerField()),
                ('max_clip', models.IntegerField()),
                ('current_clip', models.IntegerField()),
                ('image_id', models.IntegerField()),
                ('nation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Nation')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('end_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('start_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('robot_to_user_a', models.Field()),
                ('robot_to_user_b', models.Field()),
                ('team_nations', models.Field()),
                ('is_private', models.BooleanField(default=False)),
                ('result', models.TextField(default='kir')),
                ('game_mode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.GameMode')),
            ],
        ),
    ]
