# Generated by Django 2.2 on 2020-04-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.ForeignKey(db_column='wallet_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Wallet'),
        ),
    ]
