# Generated by Django 3.0.2 on 2020-02-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200213_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet',
        ),
    ]
