# Generated by Django 2.2 on 2020-03-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200213_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Account',
        ),
    ]
